# Generated by Django 2.1.7 on 2019-02-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190226_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namechat',
            old_name='user_id',
            new_name='user',
        ),
    ]
